services:
  - type: web
    name: xvm-wiki
    env: python
    plan: free   # 有料にするなら「starter」や「standard」
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install flask
    startCommand: python app.py
